server:
  port: 8085
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/activitystream_step7_usercircle
   username: root
   password: pass@word1
  jpa:
    hibernate:
      ddl-auto: update
      
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect